config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  resources :favorites, only: [:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  get 'relationships/follow'
  get 'relationships/followed'

  post 'favorites/:id', to: "favorites#create"
  resources :book_comments, only: [:create,:destroy]

  get 'search/search'

  root 'home#top'
  get 'home/about'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/search.rb
class Search < ApplicationRecord

	
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
	def search
		if params[:target] == "User"
			@users = search_user(params[:word],params[:style])
			@word = params[:word]
			render "search/search_user"
		elsif params[:target] == "Book"
			@books = search_book(params[:word],params[:style])
			@word = params[:word]
			render "search/search_book"
		end
	end

	def search_user(word,style)
		case style
			when "部分一致" then
				return User.all unless word
				User.where(["name LIKE ?", "%#{word}%"])
			when "完全一致" then
				return User.all unless word
				User.where(["name LIKE ?", "#{word}"])
			when "前方一致" then
				return User.all unless word
				User.where(["name LIKE ?", "#{word}%"])
			when "後方一致" then
				return User.all unless word
				User.where(["name LIKE ?", "%#{word}"])
			else
		end
	end

	def search_book(word,style)
		case style
			when "部分一致" then
				return Book.all unless word
				Book.where(["title LIKE ?", "%#{word}%"])
			when "完全一致" then
				return Book.all unless word
				Book.where(["title LIKE ?", "#{word}"])
			when "前方一致" then
				return Book.all unless word
				Book.where(["title LIKE ?", "#{word}%"])
			when "後方一致" then
				return Book.all unless word
				Book.where(["title LIKE ?", "%#{word}"])
			else
		end
	end

end

app/helpers/search_helper.rb
module SearchHelper



end

app/views/search/_search.html.erb
<div class="row" style="text-align:center">
	<div>
		<%= form_tag(search_search_path, method: :get) do %>
		<%= text_field_tag :word %>
		<%= select_tag(:target, options_for_select([["User", "User"], ['Book', 'Book']])) %>
		<%= select_tag(:style, options_for_select([["完全一致", "完全一致"], ['前方一致', '前方一致'],['後方一致','後方一致'],["部分一致","部分一致"]])) %>
		<%= submit_tag "検索" %>
		<% end %>
	</div>
</div>

app/views/search/search.html.erb
<div class="row">

	<div class="col-xs-12">
		<h2>search ans</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td>フォロー数：<%= follow_count(user.id) %></td>
					<td>フォロワー数：<%= followed_count(user.id) %></td>

					<!--自分なので表示しない-->
					<% if user.id == current_user.id %>
						<td></td>
					<!--すでにフォローしてる-->
					<% elsif follows?(user.id) %>
						<td><%= link_to "フォロー外す",relationship_path(user.id), method: :delete %></td>
					<!--フォローしてない-->
					<% else %>
						<td><%= link_to "フォローする",relationships_path(followed_id: user.id),method: :post %></td>
					<% end %>

					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>

app/views/search/search_book.html.erb
<div class="row">

	<div class="col-xs-12">
		<h2>Books search for "<%= @word %>"</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th></th>
					<th></th>
					<th colspan="1"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
					<tr id="book-index-ajax-<%= book.id %>">
						<%= render partial: "books/book_row", locals: {book: book,call: nil} %>
					</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/search/search_user.html.erb
<div class="row">

	<div class="col-xs-12">
		<h2>Users search for "<%= @word %>"</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>
					<td>フォロー数：<%= follow_count(user.id) %></td>
					<td>フォロワー数：<%= followed_count(user.id) %></td>

					<!--自分なので表示しない-->
					<% if user.id == current_user.id %>
						<td></td>
					<!--すでにフォローしてる-->
					<% elsif follows?(user.id) %>
						<td><%= link_to "フォロー外す",relationship_path(user.id), method: :delete %></td>
					<!--フォローしてない-->
					<% else %>
						<td><%= link_to "フォローする",relationships_path(followed_id: user.id),method: :post %></td>
					<% end %>

					<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--users一覧 -->
	</div>
</div>