config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  resources :favorites, only: [:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  get 'relationships/follow'
  get 'relationships/followed'

  post 'favorites/:id', to: "favorites#create"
  resources :book_comments, only: [:create,:destroy]

  get 'search/search'

  root 'home#top'
  get 'home/about'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user, optional: true
	belongs_to :book, optional: true
	validates :body, presence: true
end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
		def create
		@book_comment = BookComment.new(book_comment_params)
		if @book_comment.save
			@book = Book.find(@book_comment.book_id)
			@users = User.all
			@book_comments = BookComment.all
			render 'book_comments/comment_all'
			#redirect_back(fallback_location: nil)
		else
			@book_new = Book.new
			@book = Book.find(@book_comment.book_id)
			@user = User.find(@book.user_id)
			@users = User.all
			@book_comments = BookComment.all
			render 'books/show'
		end
	end
	def update
	end
	def destroy
		@book_comment = BookComment.find(params[:id])
		@book_comment.delete
		@book = Book.find(@book_comment.book_id)
		@users = User.all
		@book_comments = BookComment.all
		render :comment_all
		#redirect_back(fallback_location: nil)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:body,:book_id,:user_id)
	end
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_comment_all.html.erb
<!--コメント表示-->
<table>
	<% book_comments.each do |c| %>
	<!--コメントのbook_id == showしてるbookのid　⇒　コメント表示-->
	<% if discover_book_comment(book.id,c.book_id) %>
	<tr>
		<td>
		<%= link_to (user_path(c.user_id)) do %>
			<%= attachment_image_tag(users.find(c.user_id), :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>

			<%= users.find(c.user_id).name %>
		<% end %>

		</td>
		<td><%= c.body %></td>
		<% if c.user_id == current_user.id %>
		<td><%= link_to "Destroy", book_comment_path(c.id),method: :delete, class: "btn btn-danger",remote: true %></td>
		<% end %>
	</tr>
	<% end %>
	<% end %>
</table>

app/views/book_comments/_comment_form.html.erb
<%= form_with(model: book_comment) do |c| %>
	<!--コントローラにhiddenで見えないようにして送信-->
	<%= c.hidden_field :user_id, :value => current_user.id %>
	<%= c.hidden_field :book_id, :value => book.id %>
	<!--入力欄-->
	<%= c.text_area :body, id: "textarea2", class: "comment-text-area" %>
	<%= c.submit "送信" %>
<% end %>

app/views/book_comments/comment_all.js.erb

$("#comment_area_id").html("<%= j(render 'book_comments/comment_all', {book_comments: @book_comments, users: @users, book: @book }) %>")
$("#textarea2").val('')