config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions'
  }
  resources :users,only: [:show,:index,:edit,:update]
  resources :books
  resources :favorites, only: [:create,:destroy]
  resources :relationships, only: [:create,:destroy]
  get 'relationships/follow'
  get 'relationships/followed'

  post 'favorites/:id', to: "favorites#create"
  resources :book_comments, only: [:create,:destroy]

  get 'search/search'

  root 'home#top'
  get 'home/about'

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: '/letter_opener'
  end

end

app/models/book.rb
class Book < ApplicationRecord
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy
	belongs_to :user, optional: true
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
   before_action :authenticate_user!

  def show
    @book_new = Book.new
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @users = User.all
    @book_comments = BookComment.all
    @book_comment = BookComment.new
    @call = "show"
  end

  def index
    @book = Book.new
    @books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @call = "index"
  end

  def create
    @book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
    if @book.save #入力されたデータをdbに保存する。
      redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
    if @book.user_id != current_user.id
      redirect_to books_path
    end
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to @book, notice: "successfully updated book!"
    else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.delete
    redirect_to books_path, notice: "successfully delete book!"
  end


  private

  def book_params
    params.require(:book).permit(:title, :body,:user_id)
  end
end

app/helpers/books_helper.rb
module BooksHelper


  def favorited?(favorite_user_id,favorite_book_id)
 	  favorites = Favorite.all
 	  favorites.each do |l|
 	  if favorite_user_id == l.user_id && favorite_book_id == l.book_id
 			return true
     	end
  	end
    return false
  end

  def favorited_count(favorited_book_id)
    favorite = Favorite.all
    count = 0
    favorite.each do |l|
      if l.book_id == favorited_book_id
        count = count + 1
      end
    end
    return count
  end

  def discover_book_comment(look_book_id,book_comment_id)
      if look_book_id == book_comment_id
        return true
      end
    return false
  end

  def book_comment_count(look_book_id)
    book_comments = BookComment.all
    count = 0
    book_comments.each do |c|
      if look_book_id == c.book_id
        count += 1
      end
    end
    return count
  end

end

app/views/books/_book_row.html.erb

<td>
	<%= link_to(book.user) do %>
	<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
	<% end %>
</td>
<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>

<td><%= book.body %></td>

<% if favorited?(current_user.id, book.id) %> <!--favoriteされてる-->
<td><%= link_to favorited_count(book.id), favorite_path(id: book.id,user_id: current_user.id,call: call), method: :delete,class: "glyphicon glyphicon-heart", remote: true %></td>
<% else %><!--favoriteされてない-->
<td><%= link_to favorited_count(book.id), favorite_path(id: book.id,call: call), method: :post, class: "glyphicon glyphicon-heart-empty", remote: true %></td>
<% end %>

<td>コメント数：<%= book_comment_count(book.id) %></td>

<% if current_user.id == book.user_id && call == "show" %>
<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
<% end %>

app/views/books/_newform.html.erb
<% if book.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

  <ul>
    <% book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>


<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/book_row.js.erb
$("#book-index-ajax-<%= @book.id %>").html("<%= j(render 'books/book_row', {book: @book,call: @call}) %>")

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
						<tr id="book-index-ajax-<%= book.id %>">
							<%= render partial: "books/book_row", locals: {book: book,call: @call} %>
						</tr>
				<% end %>
			</tbody>

		</table>
	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book_new %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
			<% if @book.user_id == current_user.id%>


			<!--favoriteすると、editとdestroyは tr内で置き換わって消える-->
				
						<tr id="book-index-ajax-<%= @book.id %>">
							<%= render partial: "books/book_row", locals: {book: @book,call: @call} %>
						</tr>
					

			<!--他人のユーザーshow-->
			<% else %>
					<tr id="book-index-ajax-<%= @book.id %>">
						<%= render partial: "books/book_row", locals: {book: @book, call: @call} %>
					</tr>
			<% end %>

		</table>

		<!--Ajaxでコメント一覧呼び出し-->
		<div id="comment_area_id">
			<%= render partial: "book_comments/comment_all", locals: {book_comments: @book_comments, users: @users, book: @book } %>
		</div>


		<% if @book_comment.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@book_comment.errors.count, "error") %> prohibited this book from being saved:</h2>

			<ul>
				<% @book_comment.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
		<% end %>




		<!--Ajaxでコメント入力欄呼び出し-->
		<% if user_signed_in? %>
			<%= render partial: "book_comments/comment_form", locals: {book_comment: @book_comment, book: @book} %>
		<% end %>

	</div>
</div>